<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getFlowDetails</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQpTdHJpbmcgaXNGbG93ID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZUN1cnNv
ciwgImlzRmxvdyIpOw0KDQpTdHJpbmcgaWZjbmFtZSA9IG51bGw7DQpTdHJpbmcgc3ZjbmFtZSA9
IG51bGw7DQoNCmlmIChpc0Zsb3cgIT0gbnVsbCAmJiBpc0Zsb3cuY29udGFpbnMoIjoiKSkgew0K
ICAgIFN0cmluZ1tdIHBhcnRzID0gaXNGbG93LnNwbGl0KCI6IiwgMik7DQogICAgaWZjbmFtZSA9
IHBhcnRzWzBdLnRyaW0oKTsNCiAgICBzdmNuYW1lID0gcGFydHNbMV0udHJpbSgpOw0KfSBlbHNl
IHsNCiAgICB0aHJvdyBuZXcgU2VydmljZUV4Y2VwdGlvbigiZnVsbE5hbWUgbXVzdCBiZSBpbiBm
b3JtYXQgJ2lmY25hbWU6c3ZjbmFtZSciKTsNCn0NCg0KSURhdGEgaXMgPSBJRGF0YUZhY3Rvcnku
Y3JlYXRlKCk7DQpJRGF0YUN1cnNvciBpc0N1cnNvciA9IGlzLmdldEN1cnNvcigpOw0KSURhdGFV
dGlsLnB1dChpc0N1cnNvciwgImlmY25hbWUiLCBpZmNuYW1lKTsNCklEYXRhVXRpbC5wdXQoaXND
dXJzb3IsICJzdmNuYW1lIiwgc3ZjbmFtZSk7DQppc0N1cnNvci5kZXN0cm95KCk7DQoNCklEYXRh
VXRpbC5wdXQocGlwZWxpbmVDdXJzb3IsICJpcyIsIGlzKTsNCnBpcGVsaW5lQ3Vyc29yLmRlc3Ry
b3koKTs=</value>
</Values>
