<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">convertOASToMCP</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZyBvcGVuQVBJU3RyaW5nID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZUN1cnNvciwgIm9w
ZW5BUElTdHJpbmciKTsNClN0cmluZyBoZWFkZXJQcmVmaXggPSBJRGF0YVV0aWwuZ2V0U3RyaW5n
KHBpcGVsaW5lQ3Vyc29yLCAiaGVhZGVyUHJlZml4Iik7DQpTdHJpbmcgcGF0aFBhcmFtUHJlZml4
ID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZUN1cnNvciwgInBhdGhQYXJhbVByZWZpeCIp
Ow0KU3RyaW5nIHF1ZXJ5UHJlZml4ID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZUN1cnNv
ciwgInF1ZXJ5UHJlZml4Iik7DQpTdHJpbmcgbWNwT2JqZWN0TmFtZSA9IElEYXRhVXRpbC5nZXRT
dHJpbmcocGlwZWxpbmVDdXJzb3IsICJtY3BPYmplY3ROYW1lIik7DQpTdHJpbmcgcmVzcG9uc2VN
b2RlID0gSURhdGFVdGlsLmdldFN0cmluZyhwaXBlbGluZUN1cnNvciwgInJlc3BvbnNlTW9kZSIp
Ow0KDQpPQVMyTUNQQ29udmVydGVyIG1jcENvbnZlcnRlciA9IG5ldyBPQVMyTUNQQ29udmVydGVy
KCk7DQpTdHJpbmcgcmVzdWx0ID0gbWNwQ29udmVydGVyLmdlbmVyYXRlTWNwVG9vbFN0cmluZ0Zy
b21PQVMob3BlbkFQSVN0cmluZywgaGVhZGVyUHJlZml4LCBwYXRoUGFyYW1QcmVmaXgsIHF1ZXJ5
UHJlZml4LCBtY3BPYmplY3ROYW1lLCByZXNwb25zZU1vZGUpOw0KDQpJRGF0YVV0aWwucHV0KHBp
cGVsaW5lQ3Vyc29yLCAidG9vbEpTT05TdHJpbmciLCByZXN1bHQpOw0KcGlwZWxpbmVDdXJzb3Iu
ZGVzdHJveSgpOw==</value>
</Values>
