# Vault alias is hashiCorpVault
vault.hashiCorpVault.type=com.webmethods.is.vault.hashicorp.HashiCorpVaultConnection
vault.hashiCorpVault.enabled=true
vault.hashiCorpVault.primary=true

# Vault performance tuning
vault.hashiCorpVault.secretsCache.enabled=true
vault.hashiCorpVault.secretsCache.maxEntries=500
vault.hashiCorpVault.secretsCache.ttlSeconds=60

# Vault-specific configurations and paths
vault.hashiCorpVault.properties.VAULT_ADDR=http://localhost:8200
vault.hashiCorpVault.properties.VAULT_TOKEN=myroot
vault.hashiCorpVault.properties.SECRET_MOUNT_PATH=iwhi
vault.hashiCorpVault.properties.ENCRYPTION_KEY=iwhi-integration